name: crr_dev

channels:
  - conda-forge
  - anaconda
  
dependencies:
  - esmpy
  - numpy<2.0.0
  - ipykernel
  - matplotlib
  - pytest
  - sphinx
  - pip
  - pip:
    - -e ./crocodileregionalruckus/rm6/
    - myst_parser
    - nbsphinx