name: crr

channels:
  - conda-forge
  - anaconda
  
dependencies:
  - esmpy
  - numpy<2.0.0
  - ipykernel
  - matplotlib
  - pytest
  - sphinx
  - myst_parser # RM6 Sphinx Extension
  - nbsphinx # RM6 Sphinx Extension
  - pip
  - pip:
    - -e ./crocodileregionalruckus/rm6/