name: CrocoDash

channels:
  - conda-forge
  - anaconda
  
dependencies:
  - python>=3.11.10,<3.12
  - esmpy>=8.6.1,<8.7.0
  - pydeps>=3.0.01,<3.1.0
  - graphviz>=12.2.1,<12.3.0
  - python-graphviz>=0.20.3,<0.21.0
  - nbsphinx>=0.9.6,<0.10.0
  - pip>=24.2,<24.3
  - pip:
    - -e ./CrocoDash/rm6/
    - -e ./CrocoDash/visualCaseGen/external/ipyfilechooser/
    - -e ./CrocoDash/visualCaseGen/external/mom6_bathy/
    - -e ./CrocoDash/visualCaseGen/
    - myst_parser>=4.0.0,<4.1.0
    - -e ./
