name: croco_dash

channels:
  - conda-forge
  - anaconda
  
dependencies:
  - python>=3.12.7,<3.13.0
  - esmpy>=8.6.1,<8.7.0
  - numpy>=1.2.6.4,<1.27
  - ipykernel>=6.29.5,<6.30.0
  - matplotlib>=3.9.2,<3.10
  - pytest>=8.3.3,<8.4.0
  - sphinx>=8.1.3,<8.2.0
  - black>=24.10.0,<24.11.0
  - pip>=24.2,<24.3
  - pip:
    - -e ./crocodile_dashboard/rm6/
    - myst_parser>=4.0.0,<4.1.0
    - nbsphinx>=0.9.5,<0.10.0
    - sphinx_rtd_theme>=3.0.1,<3.1.0
    - -e ./ # CrocoDash package itself
