name: Check Raw Dataset Access

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
            submodules: recursive
      - uses: mamba-org/setup-micromamba@v2
        with:
          environment-name: CrocoDash
          environment-file: environment.yml
          cache-environment: true
          cache-downloads: true
      - name: Run link checker
        run: python docs/source/raw_data_access/check_raw_data.py
        shell: bash -el {0}
      - run: find docs/source/_static -name ".gitignore" -delete
      - name: Upload report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/source/raw_data_access
          destination_dir: reports 
          keep_files: false  
          
